name: CI

on:
  push:
    branches:
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - main  # or prod, depending on your naming convention
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest  # CI pipeline runs on Ubuntu, but ensures compatibility with CentOS

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update -y  # Ubuntu-based commands
        pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Run tests
      run: |
        pytest tests/

